export enum ActionTypeKeys {
  DISH_SELECTED = "DISH_SELECTED",
  SHOW_INFO = "SHOW_INFO",
  ADD_TO_MENU = "ADD_TO_MENU",
  REMOVE_FROM_MENU = "REMOVE_FROM_MENU",
  ADD_TO_FORBIDDEN = "ADD_TO_FORBIDDEN",
  REMOVE_FROM_FORBIDDEN = "REMOVE_FROM_FORBIDDEN"
}
